### ISSUE TITLE
KiCad 7 Docker images are not using the latest KiCad releases

### ISSUE THREAD

**Issue by ceoloide** [INTI-CMNB/kicad_auto#16]
When running `kicad-cli version` using `ghcr.io/inti-cmnb/kicad7_auto:latest` the version reported is `7.0.8` and the version reported by `setsoft/kicad_auto:nightly`is even older (<9 months as it doesn't have `kicad-cli` available).

A recent commit to KiCad 7 added the ability to import Specctra SES files in headless mode through Python, which enables automated Freerouting workflows. It would be nice to have fresh images to play with.

**Comment by set-soft** [comment]
Hi @ceoloide !

> When running `kicad-cli version` using `ghcr.io/inti-cmnb/kicad7_auto:latest` the version reported is `7.0.8` 

They aren't updated automatically. I must be sure that a new KiCad release doesn't break some feature, and it usually does because the "stable" KiCad branch is full of patches "cherry-picked" from the "unstable" branch.

> and the version reported by `setsoft/kicad_auto:nightly`is even older (<9 months as it doesn't have `kicad-cli` available).

I think you are looking for 'stable_nightly', but in any case: I'm not using the nightlies at the moment, they are changing too fast, breaking stuff every week.

> A recent commit to KiCad 7 added the ability to import Specctra SES files in headless mode through Python, which enables automated Freerouting workflows. It would be nice to have fresh images to play with.

I added a 7.0.9 stable release today, check if the patch is there.
